### ISSUE TITLE
Failed withh refresh page

### ISSUE THREAD

**Issue by jqEmprendedorVE** [nuxt/hackernews#4]
When i navigate en in the portal to comments by example https://hn.nuxtjs.org/item/15029096 return a error like that

````
Nuxt.js Error:

RangeError: Maximum call stack size exceeded
    at VueComponent.Component.options.data (server-bundle.js:258:37)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)
    at VueComponent.Component.options.data (server-bundle.js:259:30)```

**Comment by Atinux** [comment]
Sorry about this, it's fixed
